### ISSUE TITLE
AutoResetMod Button Problem

### ISSUE THREAD

**Issue by Boobies** [DuncanRuns/Seed-Based-RNG-Fabric#1]
Issues are closed for the AutoResetMod project so I'm just dropping this on the project you've made your last commit. The button is not aligned properly (nor does the golden boots texture sit on it) when using mods that add extra buttons to the main menu. An example would include Mod Menu.
![2022-02-03_02 17 37](https://user-images.githubusercontent.com/2664101/152261282-72a10f47-011e-4386-b1aa-f4c2cee1fe3a.png)

**Comment by DuncanRuns** [comment]
The mod is built for speedrunning; mods like mod menu and others are not considered due to not being legal for speedrunning.
If a pr is made to fix the issue then I would approve of it.
And the issues page for autoresetmod is closed because the only thing that appears there is people asking for a set seed version of the mod.

**Comment by Boobies** [comment]
I'm aware that there is a very specific set of mods that are accepted for official speedruns but people may do their own unofficial speedruns without any intention to actually compete.
